### ISSUE TITLE
Stop using monaco editor

### ISSUE THREAD

**Issue by KSXGitHub** [ghuntley/noyaml#17]
Why are you willing to go through such a pain of embedding an editor just for a horrible user experience (especially on mobile)? I hate your site more than I hate editing GitHub Workflow files. This fact alone make your rant loses its merit. Stop it! Just use a site generator!

**Comment by ghuntley** [comment]
noyaml.com is a art project, it is as accessible on mobile as crafting yaml on the desktop is. This is by design.

**Comment by cartermp** [comment]
lol
